apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bankai-backend
  namespace: {{ .Values.namespace }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend

  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}

  endpoints:
    - port: http
      path: /metrics
      interval: 15s